### ISSUE TITLE
Proposal for changes in the project architecture

### ISSUE THREAD

**Issue by ernstleierzopf** [ernstleierzopf/MAS-Preloaded-Apps-Scripts#1]
I will use this thread to propose changes to the project. These are (or at least it should be after we agree upon it) ordered in the chronological order in which these changes should be implemented. Please comment in this issue if you agree/disagree.
I suggest implementing these changes in smaller packages for easier review.

This issue should be adapted after steps of it were implemented to include more detail and answer occurring questions.

Checkboxes:
- [x] 1. fix Xiaomi issue #1 
- [x] 2. #3 
- [x] 3. #4 remove scripts which will not be needed after restructuring the project. The only task of this project is to 1) analyze one or multiple APK files and 2) calculate the security scoring formula. The extraction tool for firmware images is open source at `https://github.com/ernstleierzopf/AndScanner` and it does not need a dockerfile to extract a single firmware image.  The mentioned files include:
- `run.sh` (include instruction on how to run the software in `readme.md` - will be changed anyways)
- ~~`dockerfile_*`~~
- ~~`data` directory~~
- ~~move `submodules/TestCasesScripts/*` to root directory of the project and remove these directories~~
- [x] 4. #5 create small script to hash all APKs from one firmware image `hash_apks.py`.
Example usage: `python3 hash_apks.py "data/apks/husky-uq1a.240105.004-factory-498499a8" "data/apk_hashes.csv"`
- [x] 5. #6 create script to analyze a single APK file `analyze_apk.py`.
Example usage: `python3 analyze_apk.py "data/apks/husky-uq1a.240105.004-factory-498499a8/YouTube" "data/results/all_apk_hashes.csv"` -> test if hash of .apk file is found in `all_apk_hashes.csv`. Yes -> exit. No -> run all tests and append to files with all results (see #9). Hint: this uses the result directory (in this case `data/results`) and writes/creates the result files.
- [ ] 6. #7 create separate script `calculate_formula.py` to calculate the formula results using the configured permission weights in `config/methods_config.yml` and the list of app hashes created in `hash_apks.py`.
Example usage: `python3 calculate_formula.py "config/methods_config.yml" "data/apks/husky-uq1a.240105.004-factory-498499a8" "data/apk_hashes.csv"  "data/results"`. Hint: this script uses the same files created/written by the `analyze_apk.py`. Creates `formula.csv`.
- [x] 7. create script `extract_results.py` to extract all results from the merged results (in this case in `data/results`).
Example usage: `python3 extract_results.py "data/apk_hashes.csv" "data/results" "data/results/husky-1725366134_uq1a.240105.004-factory-498499a8_MD5-HASH-OF-FW"`
- [x] 7. ~~#8 change `main.py` to do all of the previous steps, namely hash all extracted APKs from the firmware image, iterate through all of them using `analyze_apk.py`, and calculate the formula (append the result to the `formula.csv` file). `main.py` must have all of the necessary arguments for all of the python scripts. The `main.py` file should use the resulting files to create one directory per firmware image with the interesting data to allow for efficient analysis.~~
- [x] 8. #9 ~~store interesting additional information of APKs such as the list of permissions and dependencies (including version?).~~
rework the structure of the result files.
~~- implement proper logging for app analysis (use logging module and have one total file for all analysis. Distinction can be made with the APK hash)~~
~~- include UNIX timestamp in each line of the analysis (these are better than dates, because if a human wants to read them, it is easily possible to let Excel, LibreOffice convert these timestamps to dates.)~~
- have four result files: `test-results.csv` (currently Report), `total-fail-counts.csv`, `findings.csv`, `formula.csv` (formula.csv includes name of vendor, firmware image name, hash of firmware image, some kind of automated encoding of the configured permission/weights (base64 encoding? - easier for comparison, worst case just include the yml data from the config), and score -> these files should be the default value for the `analyze_apk.py` script.
- [x] ~~9. previously missing~~
- [x] ~~10. #10 remove all database usage in the project. Extract data only to human readable (text, csv or other fitting formats) files.~~
- [ ] 11. Network Tests seem to not be available (NA) in any of the runs. Does this only work on real devices or why does the test not work?

#11 Very important would be to exactly define which tests were implemented (including the [ID of the MASTG test](https://mas.owasp.org/MASTG/tests/). This should be seen in the file name. The file should include a comprehensive description of what part of the document was implemented and what the goal of the test is.
